name: Terraform CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Terraform fmt (check)
        run: terraform fmt -check
      - name: Terraform init (no backend)
        run: terraform init -backend=false -input=false -no-color
      - name: Terraform validate
        run: terraform validate
